mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shiro.auth.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
   com.shiro.auth.*: trace
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616?tcpNoDelay=true
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30s
    jms:
      listener:
        max-concurrency: 8
        concurrency: 4
        acknowledge-mode: auto
      template:
        default-destination: report
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678

server:
  port: 8090


